USE DATABASE SNOWFLAKE_SAMPLE_DATA;
USE SCHEMA tpch_sf1;

SHOW TABLES;

SELECT * FROM CUSTOMER LIMIT 10;

--DISPLAY CUST DETAILS WHERE NATIONKEY IS 14
SELECT C_CUSTKEY, C_NAME,C_NATIONKEY
FROM CUSTOMER
WHERE C_NATIONKEY=14;

SELECT * FROM ORDERS;

--JOIN CUSTOMER TABLE WITH ORDERS TABLE
SELECT C.C_NAME AS CUSTOMER_NAME,
O.O_ORDERKEY,
O.O_ORDERDATE,
O.O_TOTALPRICE
FROM CUSTOMER C
JOIN ORDERS O
ON C.C_CUSTKEY=O.O_CUSTKEY
LIMIT 20;

--AGGREGATION
--SUM OF TOTALPRICE FOR EACH CUSTOMER
SELECT C.C_NAME,
SUM(O.O_TOTALPRICE) AS TOTAL_SALES
FROM CUSTOMER C
JOIN ORDERS O
ON C.C_CUSTKEY=O.O_CUSTKEY
GROUP BY C.C_NAME
ORDER BY TOTAL_SALES DESC
LIMIT 15;

SELECT * FROM ORDERS;

--ORDER DETAILS FOR THE YEAR 1996
SELECT O_ORDERKEY,O_ORDERDATE,O_TOTALPRICE
FROM ORDERS
WHERE YEAR(O_ORDERDATE)=1996
ORDER BY O_ORDERDATE
LIMIT 10;

SELECT * FROM REGION;
SELECT * FROM NATION;

--"Find the average order value (total price) for each region and display the results in descending order of average order value."
SELECT R.R_NAME AS REGION,
ROUND(AVG(O.O_TOTALPRICE),2) AS AVG_ORDER_VALUE
FROM REGION R
JOIN NATION N ON R.R_REGIONKEY=N.N_REGIONKEY
JOIN CUSTOMER C ON N.N_NATIONKEY=C.C_NATIONKEY
JOIN ORDERS O ON O.O_CUSTKEY=C.C_CUSTKEY
GROUP BY R.R_NAME
ORDER BY AVG_ORDER_VALUE DESC;

--CREATE DATABASE
CREATE OR REPLACE DATABASE MY_PRACTICE_DB;
USE MY_PRACTICE_DB;

--CREATE TABLE
CREATE OR REPLACE TABLE MY_TOP_CUSTOMERS AS
SELECT C.C_NAME,SUM(O.O_TOTALPRICE) AS TOTAL_SALES
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.CUSTOMER C
JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.ORDERS O
ON O.O_CUSTKEY=C.C_CUSTKEY
GROUP BY C.C_NAME
ORDER BY TOTAL_SALES DESC
LIMIT 20;

SELECT * FROM MY_PRACTICE_DB.PUBLIC.MY_TOP_CUSTOMERS;
