SHOW WAREHOUSES;
CREATE WAREHOUSE my_warehouse
WITH
  WAREHOUSE_SIZE = 'XSMALL'
  WAREHOUSE_TYPE = 'STANDARD'
  AUTO_SUSPEND = 300
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE
  COMMENT='This is Second Warehouse';

  CREATE WAREHOUSE sales_wh
WITH
  WAREHOUSE_SIZE = 'SMALL'
  AUTO_SUSPEND = 120
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

  DROP WAREHOUSE my_warehouse;
  
ALTER WAREHOUSE sales_wh
SET WAREHOUSE_SIZE='XSMALL'
AUTO_SUSPEND=120

ALTER WAREHOUSE sales_wh   RESUME;

ALTER WAREHOUSE sales_wh SUSPEND;

USE warehouse sales_wh;

SELECT * FROM SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_LOAD_HISTORY;

show warehouses like 'sales_wh';

create WAREHOUSE etl_wh
 MIN_CLUSTER_COUNT = 1
    MAX_CLUSTER_COUNT = 4
    SCALING_POLICY = 'ECONOMY';


