--As Provider
CREATE OR REPLACE DATABASE SALES_DB;
USE DATABASE SALES_DB;

CREATE OR REPLACE TABLE SALES (
  REGION VARCHAR,
  PRODUCT VARCHAR,
  AMOUNT NUMBER
);

INSERT INTO SALES VALUES
('South', 'Laptop', 85000),
('North', 'Mobile', 60000),
('East', 'Tablet', 30000);

CREATE OR REPLACE SHARE SALES_SHARE;

GRANT USAGE ON DATABASE SALES_DB TO SHARE SALES_SHARE;
GRANT USAGE ON SCHEMA SALES_DB.PUBLIC TO SHARE SALES_SHARE;
GRANT SELECT ON TABLE SALES_DB.PUBLIC.SALES TO SHARE SALES_SHARE;

ALTER SHARE SALES_SHARE ADD ACCOUNT = '<consumer_account_locator>';

--As Consumer
SHOW SHARES;

CREATE DATABASE SHARED_SALES_DB FROM SHARE <provider_account_locator>.SALES_SHARE;

SELECT * FROM SHARED_SALES_DB.PUBLIC.SALES;

--Cross-Cloud & Cross-Region Sharing
ALTER SHARE SALES_SHARE ENABLE REPLICATION TO ACCOUNTS IN REGION 'AWS_US_EAST_1';

-- Reader Accounts
CREATE MANAGED ACCOUNT retail_reader
  TYPE=READER,
  ADMIN_NAME = 'reader_admin'
  ADMIN_PASSWORD = 'SnowflakeReader123';
  
GRANT IMPORTED PRIVILEGES ON SHARE SALES_SHARE TO ACCOUNT retail_reader;