CREATE OR REPLACE DATABASE ITTECHGENIE_DB;
USE DATABASE ITTECHGENIE_DB;

CREATE OR REPLACE SCHEMA PUBLIC;

CREATE OR REPLACE WAREHOUSE CASE_WH
  WITH WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE
  COMMENT = 'Warehouse for Databricks integration';


GRANT USAGE ON WAREHOUSE CASE_WH TO ROLE ACCOUNTADMIN;
GRANT USAGE ON DATABASE ITTECHGENIE_DB TO ROLE ACCOUNTADMIN;
GRANT USAGE ON SCHEMA ITTECHGENIE_DB.PUBLIC TO ROLE ACCOUNTADMIN;


USE WAREHOUSE CASE_WH;
USE SCHEMA ITTECHGENIE_DB.PUBLIC;

CREATE OR REPLACE FILE FORMAT csv_file_format
TYPE = CSV
FIELD_DELIMITER = ','
SKIP_HEADER = 1
EMPTY_FIELD_AS_NULL = TRUE
TRIM_SPACE = TRUE;

CREATE OR REPLACE STAGE retail_stage
URL='azure://ittechgenieretailstore.blob.core.windows.net/raw'
CREDENTIALS=(AZURE_SAS_TOKEN='?sv=2024-11-04&ss=bfqt&srt=sco&sp=rwdlacupiytfx&se=2025-10-22T17:29:56Z&st=2025-10-22T09:14:56Z&spr=https&sig=QUglqNAlSNQm%2FGNspwCv8yBNmQDLBYtMWauDolaUO84%3D')
FILE_FORMAT = csv_file_format;

LIST @retail_stage;

SELECT *
FROM PUBLIC.RETAIL_SALES_RAW
LIMIT 10;


SELECT * FROM PUBLIC.RETAIL_SALES_SUMMARY;



