-- Create Small and Medium warehouses for testing
CREATE OR REPLACE WAREHOUSE SMALL_WH
  WITH WAREHOUSE_SIZE = 'SMALL' AUTO_SUSPEND = 300 AUTO_RESUME = TRUE;

CREATE OR REPLACE WAREHOUSE MEDIUM_WH
  WITH WAREHOUSE_SIZE = 'MEDIUM' AUTO_SUSPEND = 300 AUTO_RESUME = TRUE;

CREATE OR REPLACE TABLE TEST_PERF AS
SELECT SEQ4() AS ID, 
       RANDOM() AS VALUE1,
       RANDOM() AS VALUE2,
       RANDOM() AS VALUE3
FROM TABLE(GENERATOR(ROWCOUNT => 10000000));  -- 10 million rows

-- Run with SMALL_WH
USE WAREHOUSE SMALL_WH;
SELECT COUNT(*), AVG(VALUE1) FROM TEST_PERF;

-- Check Query History for Execution Time

-- Run with MEDIUM_WH
USE WAREHOUSE MEDIUM_WH;
SELECT COUNT(*), AVG(VALUE1) FROM TEST_PERF;

-- Compare execution times (medium should be faster)


