USE MY_PRACTICE_DB;
CREATE OR REPLACE SCHEMA MY_PRACTICE_DB.MY_SCHEMA1;

CREATE OR REPLACE TABLE sales_data (
    sale_id INT,
    amount NUMBER(10,2)
);

CREATE OR REPLACE TRANSIENT TABLE sales_stage (
    sale_id INT,
    region STRING
);

CREATE OR REPLACE TEMPORARY TABLE sales_temp (
    sale_id INT,
    discount NUMBER(5,2)
);


CREATE OR REPLACE TABLE PERMANENT_TABLE (
  ID   INT,
  NAME STRING
);
SHOW TABLES IN SCHEMA MY_PRACTICE_DB.MY_SCHEMA1;
-- Permanent tables can have up to 90 days (Enterprise)
ALTER TABLE PERMANENT_TABLE
  SET DATA_RETENTION_TIME_IN_DAYS = 3;

-- 2) Transient table
CREATE OR REPLACE TRANSIENT TABLE TRANSIENT_TABLE (
  ID   INT,
  NAME STRING
);

-- Max retention for TRANSIENT is 1 day (2 would fail)
ALTER TABLE TRANSIENT_TABLE
  SET DATA_RETENTION_TIME_IN_DAYS = 1;

-- 3) Temporary table (session-scoped)
CREATE OR REPLACE TEMPORARY TABLE TEMPORARY_TABLE (
  ID   INT,
  NAME STRING
);

SHOW TABLES IN SCHEMA MY_PRACTICE_DB.MY_SCHEMA1;

ALTER TABLE SALES_DATA SET DATA_RETENTION_TIME_IN_DAYS=7;

INSERT INTO SALES_DATA VALUES (2,'8999.00');

DROP TABLE SALES_DATA;

-- RESTORING DROPPED TABLE`
UNDROP TABLE SALES_DATA;
SELECT * FROM SALES_DATA;


